fun main()
{
    println("Student Enrolment: ")
    var a= readLine()
    println("Student Name: ")
    var b=readLine()
    println("Student branch: ")
    var c=readLine()
    println("Student class: ")
    var d=readLine()
    println("Student batch: ")
    var e=readLine()
    println("Student Collage name: ")
    var f=readLine()
    println("Student university name: ")
    var g=readLine()
    println("Student age: ")
    var h=readLine()

}